# Generated by Django 4.0.5 on 2022-06-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexter', '0002_userinvention'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvention',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
