# Generated by Django 4.0.5 on 2022-06-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dexter', '0003_userinvention_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvention',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='userinvention',
            name='img',
        ),
        migrations.RemoveField(
            model_name='userinvention',
            name='name',
        ),
    ]
