# Generated by Django 5.1 on 2024-08-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexter', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
